<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K4O38B7" failures="0" tests="12" name="com.tutorialsninja.qa.testcases.Login" time="105.030" errors="1" timestamp="2024-02-06T01:41:54 GTS" skipped="0">
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLogin" time="7.736"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLoginWithEcxelData" time="5.839">
    <error message="Keys to send should be a not null CharSequence" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at com.tutorialsninja.qa.testcases.Login.veryLoginWithEcxelData(Login.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- veryLoginWithEcxelData -->
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLogin" time="6.643"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLogin" time="9.073"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLoginWithEcxelData" time="7.835"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="veryLoginWithEcxelData" time="6.806"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithValidCredentials" time="7.217"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithInvalidCredentials" time="11.808"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithInvalidEmailAndValidPassword" time="11.933"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithValidEmailAndInvalidPassword" time="12.080"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithoutProvidingAnyCredentials" time="11.575"/>
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyForgotPasswordLinkIsAvailableOnLoginPageAndWorking" time="6.485"/>
</testsuite> <!-- com.tutorialsninja.qa.testcases.Login -->
